
#    spring.jpa.hibernate.ddl-auto=update
#        spring.datasource.url=jdbc:mysql://localhost:3306/bookshop
#        spring.datasource.username=root
#        spring.datasource.password=35115442
#        spring.servlet.multipart.max-file-size=128KB
#        spring.servlet.multipart.max-request-size=128KB
#        spring.http.multipart.enabled=false
#        spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bookshop
        username: root
        password: 35115442
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
            database: mysql
#paypal:
paypal:
    client-id: AWMswA26MJWfe7tNcTBz5ZzW9LOx4ifuDzrydpAcjeN2ERERLzZdNC5wLru3OQ7eT9Zp1XgkyeVFDLiT
    client-secret: ECI19LsLe2m49_p__pdR0otyENgJUnhXRfgEoZ-IBtGyzE66BDAdHPH1VNqIrlaZWM2JqY11baOM1Lkz
    mode: sandbox # Use #sandbox for testing and 'live' for production




